-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.bodega_produccion
(
    id_bodega serial NOT NULL,
    producto_id integer NOT NULL,
    lote_id integer NOT NULL,
    cantidad numeric(10, 2) NOT NULL,
    fecha_ingreso timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    sesion_usuario_id integer NOT NULL,
    observaciones text COLLATE pg_catalog."default",
    CONSTRAINT bodega_produccion_pkey PRIMARY KEY (id_bodega)
);

CREATE TABLE IF NOT EXISTS public.bodega_productos
(
    id_bodega_producto serial NOT NULL,
    producto_id integer NOT NULL,
    lote_id integer,
    cantidad numeric(10, 2) NOT NULL,
    fecha_produccion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    sesion_usuario_id integer,
    CONSTRAINT bodega_productos_pkey PRIMARY KEY (id_bodega_producto)
);

CREATE TABLE IF NOT EXISTS public.clientes
(
    id_cliente serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    ruc_ci character varying(20) COLLATE pg_catalog."default" NOT NULL,
    direccion character varying(255) COLLATE pg_catalog."default",
    telefono character varying(20) COLLATE pg_catalog."default",
    correo character varying(100) COLLATE pg_catalog."default",
    tipo character varying(50) COLLATE pg_catalog."default",
    estado character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Activo'::character varying,
    fecha_registro timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    contacto timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT clientes_pkey PRIMARY KEY (id_cliente),
    CONSTRAINT clientes_ruc_ci_key UNIQUE (ruc_ci)
);

CREATE TABLE IF NOT EXISTS public.detalle_compra
(
    compra_id integer NOT NULL,
    producto_id integer NOT NULL,
    cantidad numeric(14, 2) NOT NULL,
    costo_unitario numeric(14, 2) NOT NULL,
    subtotal numeric(14, 2) NOT NULL,
    CONSTRAINT detalle_compra_pkey PRIMARY KEY (compra_id, producto_id)
);

CREATE TABLE IF NOT EXISTS public.detalle_guia
(
    guia_id integer NOT NULL,
    producto_id integer NOT NULL,
    cantidad numeric(14, 2) NOT NULL,
    CONSTRAINT detalle_guia_pkey PRIMARY KEY (guia_id, producto_id)
);

CREATE TABLE IF NOT EXISTS public.detalle_venta
(
    factura_id integer NOT NULL,
    producto_id integer NOT NULL,
    cantidad numeric(14, 2) NOT NULL,
    precio_unitario numeric(14, 2) NOT NULL,
    subtotal numeric(14, 2) NOT NULL,
    CONSTRAINT detalle_venta_pkey PRIMARY KEY (factura_id, producto_id)
);

CREATE TABLE IF NOT EXISTS public.facturas_compras
(
    id_compra serial NOT NULL,
    numero_documento character varying(50) COLLATE pg_catalog."default" NOT NULL,
    proveedor_id integer NOT NULL,
    usuario_id integer NOT NULL,
    orden_compra_id integer,
    lote_id integer,
    fecha_compra date NOT NULL,
    subtotal numeric(14, 2) NOT NULL,
    total_iva numeric(14, 2) NOT NULL,
    total numeric(14, 2) NOT NULL,
    estado_pago character varying(50) COLLATE pg_catalog."default" DEFAULT 'Pendiente'::character varying,
    CONSTRAINT facturas_compras_pkey PRIMARY KEY (id_compra),
    CONSTRAINT facturas_compras_numero_documento_key UNIQUE (numero_documento)
);

CREATE TABLE IF NOT EXISTS public.facturas_ventas
(
    id_factura serial NOT NULL,
    numero_factura character varying(50) COLLATE pg_catalog."default" NOT NULL,
    cliente_id integer NOT NULL,
    usuario_id integer NOT NULL,
    fecha date NOT NULL,
    subtotal numeric(14, 2) NOT NULL,
    total_iva numeric(14, 2) NOT NULL,
    descuento numeric(14, 2) NOT NULL DEFAULT 0.00,
    total numeric(14, 2) NOT NULL,
    estado_pago character varying(50) COLLATE pg_catalog."default" DEFAULT 'Pendiente'::character varying,
    CONSTRAINT facturas_ventas_pkey PRIMARY KEY (id_factura),
    CONSTRAINT facturas_ventas_numero_factura_key UNIQUE (numero_factura)
);

CREATE TABLE IF NOT EXISTS public.guias_despacho
(
    id_guia serial NOT NULL,
    numero_guia character varying(50) COLLATE pg_catalog."default" NOT NULL,
    fecha_salida date NOT NULL,
    cliente_id integer,
    usuario_id integer,
    transportista character varying(100) COLLATE pg_catalog."default",
    placa_vehiculo character varying(20) COLLATE pg_catalog."default",
    estado character varying(50) COLLATE pg_catalog."default" DEFAULT 'Emitida'::character varying,
    CONSTRAINT guias_despacho_pkey PRIMARY KEY (id_guia),
    CONSTRAINT guias_despacho_numero_guia_key UNIQUE (numero_guia)
);

CREATE TABLE IF NOT EXISTS public.historial_auditoria
(
    id_auditoria serial NOT NULL,
    usuario_id integer NOT NULL,
    fecha_accion timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    accion text COLLATE pg_catalog."default" NOT NULL,
    tabla_afectada character varying(50) COLLATE pg_catalog."default",
    registro_id integer,
    CONSTRAINT historial_auditoria_pkey PRIMARY KEY (id_auditoria)
);

CREATE TABLE IF NOT EXISTS public.lotes_compra
(
    id_lote serial NOT NULL,
    numero_lote character varying(50) COLLATE pg_catalog."default" NOT NULL,
    proveedor_id integer,
    fecha_ingreso date NOT NULL,
    fecha_recepcion date NOT NULL,
    placa_camion character varying(20) COLLATE pg_catalog."default",
    observacion text COLLATE pg_catalog."default",
    CONSTRAINT lotes_compra_pkey PRIMARY KEY (id_lote),
    CONSTRAINT lotes_compra_numero_lote_key UNIQUE (numero_lote)
);

CREATE TABLE IF NOT EXISTS public.movimiento_bodega
(
    id_movimiento serial NOT NULL,
    producto_id integer NOT NULL,
    usuario_id integer,
    factura_id integer,
    compra_id integer,
    guia_id integer,
    registro_produccion_id integer,
    tipo_movimiento character varying(50) COLLATE pg_catalog."default" NOT NULL,
    referencia_texto character varying(100) COLLATE pg_catalog."default",
    cantidad numeric(14, 2) NOT NULL,
    fecha timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT movimiento_bodega_pkey PRIMARY KEY (id_movimiento)
);

CREATE TABLE IF NOT EXISTS public.ordenes_compras
(
    id_orden_compra serial NOT NULL,
    numero_orden character varying(50) COLLATE pg_catalog."default" NOT NULL,
    proveedor_id integer NOT NULL,
    usuario_id integer NOT NULL,
    fecha_emision date NOT NULL,
    fecha_requerida date,
    estado character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Pendiente'::character varying,
    total_estimado numeric(14, 2) NOT NULL DEFAULT 0.00,
    CONSTRAINT ordenes_compras_pkey PRIMARY KEY (id_orden_compra),
    CONSTRAINT ordenes_compras_numero_orden_key UNIQUE (numero_orden)
);

CREATE TABLE IF NOT EXISTS public.ordenes_produccion
(
    id_orden_produccion serial NOT NULL,
    numero_op character varying(50) COLLATE pg_catalog."default" NOT NULL,
    usuario_id integer NOT NULL,
    producto_terminado_id integer NOT NULL,
    fecha_emision date NOT NULL,
    cantidad_planificada numeric(14, 2) NOT NULL,
    merma_tolerada numeric(5, 2) DEFAULT 1.00,
    estado character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Pendiente'::character varying,
    CONSTRAINT ordenes_produccion_pkey PRIMARY KEY (id_orden_produccion),
    CONSTRAINT ordenes_produccion_numero_op_key UNIQUE (numero_op)
);

CREATE TABLE IF NOT EXISTS public.parametrizacion
(
    id_param serial NOT NULL,
    clave character varying(50) COLLATE pg_catalog."default" NOT NULL,
    valor_texto character varying(255) COLLATE pg_catalog."default",
    valor_numero numeric(12, 2),
    valor_fecha date,
    descripcion text COLLATE pg_catalog."default",
    fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    sesion_usuario_id integer,
    CONSTRAINT parametrizacion_pkey PRIMARY KEY (id_param),
    CONSTRAINT parametrizacion_clave_key UNIQUE (clave)
);

CREATE TABLE IF NOT EXISTS public.productos
(
    id_producto serial NOT NULL,
    codigo_interno character varying(20) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(255) COLLATE pg_catalog."default",
    tipo_producto character varying(50) COLLATE pg_catalog."default",
    unidad_medida character varying(10) COLLATE pg_catalog."default" NOT NULL,
    stock_actual numeric(14, 2) NOT NULL DEFAULT 0,
    stock_minimo numeric(14, 2) NOT NULL DEFAULT 0,
    precio_costo numeric(14, 2) NOT NULL DEFAULT 0,
    precio_unitario numeric(14, 2) NOT NULL DEFAULT 0,
    estado character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Activo'::character varying,
    CONSTRAINT productos_pkey PRIMARY KEY (id_producto),
    CONSTRAINT productos_codigo_interno_key UNIQUE (codigo_interno)
);

CREATE TABLE IF NOT EXISTS public.proveedores
(
    id_proveedor serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    ruc_ci character varying(20) COLLATE pg_catalog."default" NOT NULL,
    direccion character varying(255) COLLATE pg_catalog."default",
    telefono character varying(20) COLLATE pg_catalog."default",
    contacto_venta character varying(100) COLLATE pg_catalog."default",
    correo character varying(100) COLLATE pg_catalog."default",
    estado character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Activo'::character varying,
    CONSTRAINT proveedores_pkey PRIMARY KEY (id_proveedor),
    CONSTRAINT proveedores_ruc_ci_key UNIQUE (ruc_ci)
);

CREATE TABLE IF NOT EXISTS public.usuarios
(
    id_usuario serial NOT NULL,
    nombre_usuario character varying(100) COLLATE pg_catalog."default" NOT NULL,
    usuario character varying(50) COLLATE pg_catalog."default" NOT NULL,
    password character varying(100) COLLATE pg_catalog."default" NOT NULL,
    rol character varying(50) COLLATE pg_catalog."default",
    estado character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Activo'::character varying,
    CONSTRAINT usuarios_pkey PRIMARY KEY (id_usuario),
    CONSTRAINT usuarios_usuario_key UNIQUE (usuario)
);

ALTER TABLE IF EXISTS public.bodega_produccion
    ADD CONSTRAINT bodega_produccion_lote_id_fkey FOREIGN KEY (lote_id)
    REFERENCES public.lotes_compra (id_lote) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.bodega_produccion
    ADD CONSTRAINT bodega_produccion_producto_id_fkey FOREIGN KEY (producto_id)
    REFERENCES public.productos (id_producto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.bodega_produccion
    ADD CONSTRAINT bodega_produccion_sesion_usuario_id_fkey FOREIGN KEY (sesion_usuario_id)
    REFERENCES public.usuarios (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.bodega_productos
    ADD CONSTRAINT bodega_productos_lote_id_fkey FOREIGN KEY (lote_id)
    REFERENCES public.lotes_compra (id_lote) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.bodega_productos
    ADD CONSTRAINT bodega_productos_producto_id_fkey FOREIGN KEY (producto_id)
    REFERENCES public.productos (id_producto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.bodega_productos
    ADD CONSTRAINT bodega_productos_sesion_usuario_id_fkey FOREIGN KEY (sesion_usuario_id)
    REFERENCES public.usuarios (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detalle_compra
    ADD CONSTRAINT detalle_compra_compra_id_fkey FOREIGN KEY (compra_id)
    REFERENCES public.facturas_compras (id_compra) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.detalle_compra
    ADD CONSTRAINT detalle_compra_producto_id_fkey FOREIGN KEY (producto_id)
    REFERENCES public.productos (id_producto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.detalle_guia
    ADD CONSTRAINT detalle_guia_guia_id_fkey FOREIGN KEY (guia_id)
    REFERENCES public.guias_despacho (id_guia) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.detalle_guia
    ADD CONSTRAINT detalle_guia_producto_id_fkey FOREIGN KEY (producto_id)
    REFERENCES public.productos (id_producto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.detalle_venta
    ADD CONSTRAINT detalle_venta_factura_id_fkey FOREIGN KEY (factura_id)
    REFERENCES public.facturas_ventas (id_factura) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.detalle_venta
    ADD CONSTRAINT detalle_venta_producto_id_fkey FOREIGN KEY (producto_id)
    REFERENCES public.productos (id_producto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.facturas_compras
    ADD CONSTRAINT facturas_compras_lote_id_fkey FOREIGN KEY (lote_id)
    REFERENCES public.lotes_compra (id_lote) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.facturas_compras
    ADD CONSTRAINT facturas_compras_orden_compra_id_fkey FOREIGN KEY (orden_compra_id)
    REFERENCES public.ordenes_compras (id_orden_compra) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.facturas_compras
    ADD CONSTRAINT facturas_compras_proveedor_id_fkey FOREIGN KEY (proveedor_id)
    REFERENCES public.proveedores (id_proveedor) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.facturas_compras
    ADD CONSTRAINT facturas_compras_usuario_id_fkey FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.facturas_ventas
    ADD CONSTRAINT facturas_ventas_cliente_id_fkey FOREIGN KEY (cliente_id)
    REFERENCES public.clientes (id_cliente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.facturas_ventas
    ADD CONSTRAINT facturas_ventas_usuario_id_fkey FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.guias_despacho
    ADD CONSTRAINT guias_despacho_cliente_id_fkey FOREIGN KEY (cliente_id)
    REFERENCES public.clientes (id_cliente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.guias_despacho
    ADD CONSTRAINT guias_despacho_usuario_id_fkey FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.historial_auditoria
    ADD CONSTRAINT historial_auditoria_usuario_id_fkey FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.lotes_compra
    ADD CONSTRAINT lotes_compra_proveedor_id_fkey FOREIGN KEY (proveedor_id)
    REFERENCES public.proveedores (id_proveedor) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.movimiento_bodega
    ADD CONSTRAINT movimiento_bodega_compra_id_fkey FOREIGN KEY (compra_id)
    REFERENCES public.facturas_compras (id_compra) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.movimiento_bodega
    ADD CONSTRAINT movimiento_bodega_factura_id_fkey FOREIGN KEY (factura_id)
    REFERENCES public.facturas_ventas (id_factura) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.movimiento_bodega
    ADD CONSTRAINT movimiento_bodega_guia_id_fkey FOREIGN KEY (guia_id)
    REFERENCES public.guias_despacho (id_guia) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.movimiento_bodega
    ADD CONSTRAINT movimiento_bodega_producto_id_fkey FOREIGN KEY (producto_id)
    REFERENCES public.productos (id_producto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.movimiento_bodega
    ADD CONSTRAINT movimiento_bodega_usuario_id_fkey FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.ordenes_compras
    ADD CONSTRAINT ordenes_compras_proveedor_id_fkey FOREIGN KEY (proveedor_id)
    REFERENCES public.proveedores (id_proveedor) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.ordenes_compras
    ADD CONSTRAINT ordenes_compras_usuario_id_fkey FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.ordenes_produccion
    ADD CONSTRAINT ordenes_produccion_producto_terminado_id_fkey FOREIGN KEY (producto_terminado_id)
    REFERENCES public.productos (id_producto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ordenes_produccion
    ADD CONSTRAINT ordenes_produccion_usuario_id_fkey FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.parametrizacion
    ADD CONSTRAINT parametrizacion_sesion_usuario_id_fkey FOREIGN KEY (sesion_usuario_id)
    REFERENCES public.usuarios (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;